[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  targetPort = 8080
  port = 8888
  publish = "dist"

# 由于已经改为hash模式，不再需要此重定向规则
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
